### ISSUE TITLE
It's not building

### ISSUE THREAD

**Issue by mingodad** [finiteloop/compiler#1]
When trying to build this project it seems to be missing some llvm libraries and also I'm getting an error due to a missing include in core/error.c:
```
@@ -12,10 +12,11 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
 #include "error.h"
 
+#include <string.h>
 #include <unistd.h>
 
 namespace compiler {
 
 // Returns the given path with the current working directory prefix removed.

```

**Comment by finiteloop** [comment]
Hey, I mainly use a Mac, which has both an antiquated version of Bison and some differences in libc.

I submitted a few fixes after testing on Linux. Let me know if you continue to see any problems!

**Comment by finiteloop** [comment]
Re: your LLVM comment: make sure you run

    git submodule init
    git submodule update

Before building - this depends on LLVM as a git submodule.

**Comment by mingodad** [comment]
Hello Bret !
Thanks for the fixes !
But for me on ubuntu 18.04 it still doesn't build.
I did a `git submodule update ext/uft8` and used my own installed `clang-llvm-11` (I think that requiring to build llvm is not a good idea).
I manage to build after add the llvm libs from the output of `llvm-config --libs` and also needed to add `-lpthread -ldl -lz  -ltinfo`.

**Comment by finiteloop** [comment]
The build is not designed to use installed LLVM, but the CMake files from the git submodule.

**Comment by finiteloop** [comment]
Run these commands to build:

    $ git submodule init
    $ git submodule update
    $ cmake -H. -Bbuild
    $ cmake --build build --target compiler
    $ ./build/compiler
